import { dateTimeLocalFromStamp, timezoneOffsetFromStamp } from "./date-utils";
import { defaultDeviationTable, defaultMainEngine, defaultWindDriftTable, normalizeDeviationTable, normalizeWindDriftTable, type Boat, type BoatForm, type CrewForm, type LineForm, type LogLine, type LogSheet, type PersistedLogbook, type SheetForm } from "../../models/logbook";
export const emptyBoat: Boat = { id: "", archived: false, name: "", type: "Sail", registration: "", flagState: "", homePort: "", owner: "", dimensions: "", logfactor: 1, yachtData: { Manufacturer: "", MMSI: "", Safety: "" }, deviationTable: defaultDeviationTable(), windDriftTable: defaultWindDriftTable(), engines: [defaultMainEngine()], image: undefined };
export const emptySheet: LogSheet = { id: "", title: "", status: "Draft", boatId: "", route: { from: "", to: "", departed: "", arrived: "" }, crew: [], watchPlan: [], technicalChecks: [], image: undefined, lines: [] };
export const defaultLogbook: PersistedLogbook = { boats: [], crewMembers: [], sheets: [] };

export const defaultSheetForm = (boatId: string): SheetForm => ({ title: "", status: "Draft", boatId, fromDate: new Date().toISOString().slice(0, 10), toDate: new Date().toISOString().slice(0, 10), from: "", to: "", fromTime: "", toTime: "", fromTimezone: timezoneOffsetFromStamp(""), toTimezone: timezoneOffsetFromStamp(""), image: undefined });
export const defaultBoatForm: BoatForm = { name: "", type: "Sail", registration: "", flagState: "", homePort: "", owner: "", dimensions: "", logfactor: 1, manufacturer: "", mmsi: "", safety: "", deviationTable: defaultDeviationTable(), windDriftTable: defaultWindDriftTable(), engines: [defaultMainEngine()], image: undefined };
export const defaultLineForm: LineForm = { id: "", time: "", position: "", latitude: "", longitude: "", weather: "", weatherRemark: "", temperature: "", temperatureUnit: "°C", barometer: "", windDirection: "", windStrength: "", windUnit: "bft", waves: "", seaUnit: "m", tide: "", tideUnit: "m", moon: "", compassCourse: "", deviation: "", magneticCourse: "", variation: "", trueCourse: "", windDrift: "", courseThroughWater: "", currentDrift: "", courseOverGround: "", speedKn: "", logNm: "", sailMiles: "", sailNote: "", motorMiles: "", motorHours: "", engineHours: {}, motorNote: "", remarks: "" };
export const defaultCrewForm: CrewForm = { id: "", name: "", nationality: "", role: "", address: "", certificate: "", dateOfBirth: "", placeOfBirth: "", gender: "", identityDocumentType: "", identityDocumentNumber: "", identityDocumentIssuingDate: "", identityDocumentExpiryDate: "", isPrimary: false, image: undefined };

export const boatToForm = (boat: Boat): BoatForm => ({ name: boat.name, type: boat.type, registration: boat.registration, flagState: boat.flagState, homePort: boat.homePort, owner: boat.owner, dimensions: boat.dimensions, logfactor: boat.logfactor > 0 ? boat.logfactor : 1, manufacturer: boat.yachtData.Manufacturer === "—" ? "" : boat.yachtData.Manufacturer, mmsi: boat.yachtData.MMSI === "—" ? "" : boat.yachtData.MMSI, safety: boat.yachtData.Safety === "To be completed" ? "" : boat.yachtData.Safety, deviationTable: normalizeDeviationTable(boat.deviationTable), windDriftTable: normalizeWindDriftTable(boat.windDriftTable), engines: boat.engines?.length ? boat.engines : [defaultMainEngine()], image: boat.image });
export const sheetToForm = (sheet: LogSheet): SheetForm => ({ title: sheet.title, status: sheet.status, boatId: sheet.boatId, from: sheet.route.from, to: sheet.route.to, fromDate: dateTimeLocalFromStamp(sheet.route.departed).split("T")[0] ?? "", toDate: dateTimeLocalFromStamp(sheet.route.arrived).split("T")[0] ?? "", fromTime: timeFromRouteStamp(sheet.route.departed), toTime: timeFromRouteStamp(sheet.route.arrived), fromTimezone: timezoneOffsetFromStamp(sheet.route.departed), toTimezone: timezoneOffsetFromStamp(sheet.route.arrived), image: sheet.image });
export const lineToForm = (line: LogLine): LineForm => ({ ...Object.fromEntries(Object.entries(line).filter(([key]) => key !== "engineHours").map(([key, value]) => [key, String(value ?? "")])), engineHours: Object.fromEntries(Object.entries(line.engineHours ?? {}).map(([id, value]) => [id, String(value)])) }) as LineForm;
export const crewToForm = (crew: Partial<CrewForm>): CrewForm => ({ id: crew.id ?? "", name: crew.name ?? "", nationality: crew.nationality ?? "", role: crew.role ?? "", address: crew.address ?? "", certificate: crew.certificate ?? "", dateOfBirth: crew.dateOfBirth ?? "", placeOfBirth: crew.placeOfBirth ?? "", gender: crew.gender ?? "", identityDocumentType: crew.identityDocumentType ?? "", identityDocumentNumber: crew.identityDocumentNumber ?? "", identityDocumentIssuingDate: crew.identityDocumentIssuingDate ?? "", identityDocumentExpiryDate: crew.identityDocumentExpiryDate ?? "", isPrimary: crew.isPrimary ?? false, image: crew.image });

function timeFromRouteStamp(value: string) {
  return dateTimeLocalFromStamp(value).split("T")[1] ?? "";
}
