export type DistanceUnit = "m" | "ft";
export type WindUnit = "bft" | "kn";

export type LogLine = {
  time: string;
  position: string;
  latitude: number;
  longitude: number;
  weather: string;
  weatherRemark: string;
  temperature: number;
  barometer: number;
  windDirection: string;
  windStrength: number;
  windUnit: WindUnit;
  waves: number;
  seaUnit: DistanceUnit;
  tide: number;
  tideUnit: DistanceUnit;
  moon: string;
  compassCourse: number;
  deviation: number;
  magneticCourse: number;
  variation: number;
  trueCourse: number;
  windDrift: number;
  courseThroughWater: number;
  currentDrift: number;
  courseOverGround: number;
  speedKn: number;
  logNm: number;
  sailMiles: number;
  sailNote: string;
  motorMiles: number;
  motorHours: number;
  motorNote: string;
  remarks: string;
};
